"""Evaluation helpers and the model comparison report (spec §22–23, §27)."""

from __future__ import annotations

import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from sklearn.metrics import (  # noqa: E402
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

from ml.proba import ordered_proba  # noqa: E402,F401  (re-exported for training scripts)
from ml.target import RISK_LABELS  # noqa: E402


def evaluate(model, X, y) -> dict:
    y = pd.Series(y).astype(str)
    pred = model.predict(X)
    proba = ordered_proba(model, X)
    report = classification_report(y, pred, labels=RISK_LABELS, output_dict=True, zero_division=0)
    onehot = np.stack([(y == label).to_numpy() for label in RISK_LABELS], axis=1).astype(float)

    started = time.perf_counter()
    for i in range(50):
        model.predict_proba(X.iloc[[i]])
    latency_ms = (time.perf_counter() - started) / 50 * 1000

    return {
        "accuracy": accuracy_score(y, pred),
        "precision_macro": precision_score(y, pred, average="macro", zero_division=0),
        "recall_macro": recall_score(y, pred, average="macro", zero_division=0),
        "f1_macro": f1_score(y, pred, average="macro", zero_division=0),
        "precision_weighted": precision_score(y, pred, average="weighted", zero_division=0),
        "recall_weighted": recall_score(y, pred, average="weighted", zero_division=0),
        "f1_weighted": f1_score(y, pred, average="weighted", zero_division=0),
        "per_class": {label: {k: report[label][k] for k in ("precision", "recall", "f1-score", "support")} for label in RISK_LABELS},
        "confusion_matrix": confusion_matrix(y, pred, labels=RISK_LABELS).tolist(),
        # One-vs-rest AUC per class, averaged (computed by class name; sklearn requires sorted labels otherwise).
        "roc_auc_ovr_macro": float(np.mean([roc_auc_score(onehot[:, i], proba[:, i]) for i in range(len(RISK_LABELS))])),
        # Why: sklearn's log_loss assumes alphabetical columns; compute directly on the name-ordered matrix.
        "log_loss": float(-np.mean(np.log(np.clip((proba * onehot).sum(axis=1), 1e-15, 1.0)))),
        "brier_multiclass": float(np.mean(np.sum((proba - onehot) ** 2, axis=1))),
        "mean_max_probability": float(proba.max(axis=1).mean()),
        "latency_ms_single_row": latency_ms,
    }


def save_confusion_matrix(matrix, title: str, path) -> None:
    fig, ax = plt.subplots(figsize=(4.2, 3.6), dpi=130)
    m = np.array(matrix)
    ax.imshow(m, cmap="Blues")
    ax.set_xticks(range(3), RISK_LABELS)
    ax.set_yticks(range(3), RISK_LABELS)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual (constructed target)")
    ax.set_title(title, fontsize=10)
    for i in range(3):
        for j in range(3):
            ax.text(j, i, f"{m[i, j]:,}", ha="center", va="center", color="white" if m[i, j] > m.max() / 2 else "black", fontsize=9)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def _f(v, digits=3):
    return f"{v:.{digits}f}"


def write_report(path, *, results, ablation, importance, selection, meta, class_dist) -> None:
    from ml.config import MODEL_DISPLAY_NAMES as NAMES

    lines = [
        "# Model comparison — FinAware financial risk",
        "",
        f"Generated by `python -m ml.train` on {meta['trained_at']}. All numbers come from running the code on",
        f"`personal_finance_zar.csv` (SHA-256 `{meta['data_sha256'][:12]}…`). Target: `risk_tier` version "
        f"{meta['target_version']} (**status: {meta['target_status']}**).",
        "",
    ]
    if meta["target_status"] != "approved":
        lines += [
            "> **PROVISIONAL.** The constructed target has not yet been approved by the supervisor. These results",
            "> show the method working end-to-end. After approval (or any change to the rubric), re-run",
            "> `python -m ml.train` and this report is regenerated.",
            "",
        ]
    lines += [
        "## Method",
        "",
        f"- Stratified {int((1 - meta['test_size']) * 100)}/{int(meta['test_size'] * 100)} train/test split, `random_state={meta['random_state']}`: "
        f"{meta['train_rows']:,} training and {meta['test_rows']:,} test records.",
        f"- One sklearn Pipeline per model (feature engineering → StandardScaler + OneHotEncoder(handle_unknown='ignore') → model), fitted on the training split only.",
        f"- Hyper-parameters chosen by {meta['cv_folds']}-fold stratified cross-validation on the training split (scoring: macro F1). Small grids, listed below.",
        "- SVM probabilities come from `CalibratedClassifierCV(SVC, method='sigmoid', cv=3)`, replacing the deprecated `SVC(probability=True)` (defect D12).",
        f"- Model inputs ({len(meta['raw_inputs'])} raw → {len(meta['model_features'])} model features): {', '.join(meta['raw_inputs'])}; plus the dataset ratios and engineered features.",
        "",
        "### Class distribution of the constructed target",
        "",
        "| Tier | Records | % |",
        "|---|---|---|",
    ]
    lines += [f"| {t} | {int(r['records']):,} | {r['percentage']:.2f} |" for t, r in class_dist.iterrows()]
    lines += [
        "",
        "## Results on the held-out test set",
        "",
        "| Model | Accuracy | Macro P | Macro R | Macro F1 | Weighted F1 | High recall | ROC AUC (OvR) | Log loss | CV macro F1 (mean ± sd) | ms / prediction |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for key, r in results.items():
        m = r["test"]
        lines.append(
            f"| {NAMES[key]} | {_f(m['accuracy'])} | {_f(m['precision_macro'])} | {_f(m['recall_macro'])} | **{_f(m['f1_macro'])}** | "
            f"{_f(m['f1_weighted'])} | {_f(m['per_class']['High']['recall'])} | {_f(m['roc_auc_ovr_macro'])} | {_f(m['log_loss'])} | "
            f"{_f(r['cv_f1_macro_mean'])} ± {_f(r['cv_f1_macro_std'])} | {m['latency_ms_single_row']:.1f} |"
        )
    lines += ["", "### Per-class precision / recall / F1", ""]
    lines += ["| Model | " + " | ".join(f"{t} P | {t} R | {t} F1" for t in RISK_LABELS) + " |", "|---|" + "---|" * 9]
    for key, r in results.items():
        pc = r["test"]["per_class"]
        lines.append(f"| {NAMES[key]} | " + " | ".join(
            f"{_f(pc[t]['precision'])} | {_f(pc[t]['recall'])} | {_f(pc[t]['f1-score'])}" for t in RISK_LABELS) + " |")
    lines += ["", "### Confusion matrices (rows = actual, columns = predicted; Low, Medium, High)", ""]
    for key, r in results.items():
        cm = r["test"]["confusion_matrix"]
        lines.append(f"- **{NAMES[key]}**: `{cm}` — ![{key}](confusion_{key}.png)")
    lines += ["", "### Hyper-parameter search", "", "| Model | Grid | Selected |", "|---|---|---|"]
    for key, r in results.items():
        lines.append(f"| {NAMES[key]} | `{r['grid']}` | `{r['best_params']}` |")

    lines += [
        "",
        "## Global feature importance (permutation importance, spec §27)",
        "",
        f"Drop in test macro F1 when one raw input is shuffled ({importance['n_rows']:,}-record stratified test sample, "
        f"{importance['n_repeats']} repeats). Derived ratios are recomputed from the shuffled input, so each row shows the full effect of that input.",
        "",
        "| Input | " + " | ".join(NAMES[k] for k in results) + " |",
        "|---|" + "---|" * len(results),
    ]
    inputs = list(next(iter(importance["by_model"].values())).keys())
    inputs.sort(key=lambda f: -np.mean([importance["by_model"][k][f]["mean"] for k in results]))
    for feat in inputs:
        lines.append(f"| {feat} | " + " | ".join(
            f"{importance['by_model'][k][feat]['mean']:.3f} ± {importance['by_model'][k][feat]['std']:.3f}" for k in results) + " |")

    lines += [
        "",
        "## Ablation — models trained WITHOUT the rubric's inputs (circularity check, spec §20)",
        "",
        f"Inputs: {', '.join(ablation['inputs'])}. Income, expenses, repayment, savings, credit score and every ratio built from them are removed.",
        "",
        "| Model | Accuracy | Macro F1 | High recall |",
        "|---|---|---|---|",
    ]
    for key, m in ablation["results"].items():
        lines.append(f"| {NAMES[key]} | {_f(m['accuracy'])} | {_f(m['f1_macro'])} | {_f(m['per_class']['High']['recall'])} |")
    lines += [
        "",
        "Interpretation: the gap between these scores and the main results measures how much the models rely on the",
        "same values the constructed target was calculated from. The main models reproduce the rubric; they did not",
        "discover financial risk independently.",
        "",
        "## Final model selection (spec §23)",
        "",
        f"**Selected: {NAMES[selection['selected']]}** (model version {meta['model_version']}).",
        "",
        "Rule fixed before training: rank by test macro F1. Among models within "
        f"{selection['tolerance']} macro F1 of the best, prefer a tree-based model because it supports exact per-user",
        "explanations with SHAP TreeExplainer (spec §26) and fast inference; then prefer higher High-risk recall, then lower log loss.",
        "",
    ]
    lines += [f"- {reason}" for reason in selection["reasons"]]
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
