"""Load the approved artefacts and produce a prediction (spec §24–25, §35). Fixes handoff defects D6/D10/D11.

The service returns prediction + drivers only. Recommendations are generated by the Financial API Service
(Node), as drawn in the sequence diagram.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from ml.config import ARTIFACT_DIR, RAW_INPUTS
from ml.explain import Explainer
from ml.features import build_features
from ml.proba import ordered_proba
from ml.target import RISK_LABELS

# riskScore (Decision D-3): 0–100, rises with predicted risk. riskLevel is always the most probable class.
RISK_SCORE_WEIGHTS = {"Low": 0.0, "Medium": 0.5, "High": 1.0}


class ModelUnavailable(RuntimeError):
    pass


class PredictionFailed(RuntimeError):
    pass


def risk_score(probabilities: dict[str, float]) -> float:
    return round(100 * sum(RISK_SCORE_WEIGHTS[k] * probabilities[k] for k in RISK_LABELS), 1)


class Predictor:
    def __init__(self, artifact_dir: Path = ARTIFACT_DIR):
        try:
            self.pipeline = joblib.load(artifact_dir / "pipeline.joblib")
            self.metadata = json.loads((artifact_dir / "model_metadata.json").read_text())
            self.schema = json.loads((artifact_dir / "feature_schema.json").read_text())
        except FileNotFoundError as exc:
            raise ModelUnavailable(f"Model artefact missing: {Path(exc.filename).name}") from exc
        self.explainer = Explainer(self.pipeline)

    def warnings_for(self, payload: dict) -> list[dict]:
        warnings = []
        for field, spec in self.schema["inputs"].items():
            value = payload[field]
            if spec["type"] == "category" and value not in spec["allowed"]:
                warnings.append({"code": "UNKNOWN_CATEGORY", "field": field,
                                 "message": f"'{value}' was not seen in training; it is treated as neutral."})
            if spec["type"] == "number" and not (spec["training_min"] <= value <= spec["training_max"]):
                warnings.append({"code": "OUTSIDE_TRAINING_RANGE", "field": field,
                                 "message": f"{value} is outside the training range {spec['training_min']:g}–{spec['training_max']:g}; "
                                            "the prediction is less reliable."})
        return warnings

    def predict(self, payload: dict) -> dict:
        raw = pd.DataFrame([{k: payload[k] for k in RAW_INPUTS}])
        try:
            proba = ordered_proba(self.pipeline, raw)[0]
            probabilities = {label: float(p) for label, p in zip(RISK_LABELS, proba)}
            level = max(probabilities, key=probabilities.get)
            if not math.isclose(sum(probabilities.values()), 1.0, abs_tol=1e-6):
                raise PredictionFailed(f"Probabilities sum to {sum(probabilities.values())}, not 1")
            if level != str(self.pipeline.predict(raw)[0]):
                raise PredictionFailed("Predicted tier does not match the highest probability")
            drivers = self.explainer.explain(raw)
            features = build_features(raw).iloc[0]
        except PredictionFailed:
            raise
        except Exception as exc:  # noqa: BLE001 — surfaced as a structured PREDICTION_FAILED error
            raise PredictionFailed(str(exc)) from exc

        return {
            "riskLevel": level,
            "riskScore": risk_score(probabilities),
            "predictedProbability": round(probabilities[level], 6),
            "probabilities": {k: round(v, 6) for k, v in probabilities.items()},
            "topDrivers": drivers,
            "explanationMethod": self.explainer.method,
            "indicators": {
                "debtToIncomeRatio": float(features["debt_to_income_ratio"]),
                "expenseToIncomeRatio": round(float(features["expense_to_income_ratio"]), 4),
                "savingsToIncomeRatio": float(features["savings_to_income_ratio"]),
                "savingsCoverageMonths": round(float(features["savings_coverage_months"]), 2),
                "disposableIncome": round(float(features["disposable_income_zar"]), 2),
                "monthlySurplusAfterEmi": round(float(features["monthly_surplus_after_emi_zar"]), 2),
                "loanToIncomeRatio": round(float(features["loan_to_income_ratio"]), 4),
            },
            "model": {"name": self.metadata["model"], "version": self.metadata["model_version"]},
            "targetVersion": self.metadata["target_version"],
            "targetStatus": self.metadata["target_status"],
            "warnings": self.warnings_for(payload),
        }


def to_native(value):
    """Convert numpy scalars recursively so FastAPI can serialise the response."""
    if isinstance(value, dict):
        return {k: to_native(v) for k, v in value.items()}
    if isinstance(value, list):
        return [to_native(v) for v in value]
    if isinstance(value, np.generic):
        return value.item()
    return value
